// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:75a0fe37-41d8-4d1e-aea1-13fe2818309e',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'lareposteriagdl-hosting-mobilehub-180347528',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2wdmssw6mmujk.cloudfront.net',
    'aws_mobile_analytics_app_id': '29c0a18ea57b4bd9b6b0436d55ddd9a9',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '89f3eb6f-108d-4da1-bc04-05343f893028',
    'aws_project_name': 'La-reposteria-GDL',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'lareposteriagdl-mobilehub-180347528',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_pbIEgDcSU',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '6g34on9f4qas3hkrbmon7pcc4v',
}

export default awsmobile;
